sonar.projectKey=PepeTonin_sqa-social-media
sonar.organization=pepetonin

sonar.projectName=sqa-social-media
sonar.projectVersion=1.0

sonar.sources=api/src/main,client/src
sonar.tests=api/src/test,client/src

sonar.sourceEncoding=UTF-8

sonar.java.binaries=api/target/classes
sonar.javascript.lcov.reportPaths=client/coverage/lcov.info

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/target/**,**/.next/**
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx,**/*Test.java